rails/config/routes.rb
Rails.application.routes.draw do
  get 'pages/home', to: 'pages#home', as: :get_started
  get 'pages/info', to: 'pages#info', as: :info

  resources :job_applications do
    resources :interviews, except: %i[index]
  end
  resources :users, except: %i[index]
  resources :sessions, only: %i[new create] do
    delete :destroy, on: :collection
  end
  post 'sessions/create', to: 'sessions#create', as: 'login'

  resources :configurations, only: [] do
    get :ios, on: :collection
  end

  root 'pages#home'
end

rails/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  has_many :job_applications, dependent: :destroy

  validates :password, on: [:create, :password_change], presence: true, length: { minimum: 8 }
  validates :email,
    format: { with: URI::MailTo::EMAIL_REGEXP },
    uniqueness: { case_sensitive: false }

  normalizes :email, with: -> { _1.strip.downcase }
end

rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :redirect_if_authenticated, except: %i[destroy edit]
  before_action :set_user, only: %i[ show edit update destroy ]

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: "User was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    ActiveRecord::Base.transaction do
      @user.job_applications.each do |job_application|
        job_application.interviews.delete_all
      end

      @user.job_applications.delete_all
      @user.destroy!
    end

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

rails/app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :password %>
    <%= form.password_field :password, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :passwor_confirmation %>
    <%= form.password_field :password_confirmation, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-ptpurple text-white inline-block font-medium cursor-pointer w-full" %>
  </div>
<% end %>

rails/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= user.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= user.email %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this user", user, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this user", edit_user_path(user), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

rails/app/views/users/edit.html.erb
<% content_for(:title, "Edit account") %>

<div class="mx-auto md:w-2/3 w-full pb-6">
  <h1 class="font-bold text-2xl">Edit your account</h1>

  <%= render "form", user: @user %>

  <hr class="my-4">

  <%= button_to "Sign out", sessions_path, method: :delete, class: "text-white bg-gray-500 hover:bg-pt-orange focus:ring-4 font-medium rounded-lg px-5 py-3 mr-2 focus:outline-none w-full" %>

  <hr class="my-4">

  <p class="text-gray-700 text-sm mb-3">Delete my account and all data related to it.</p>
  <%= button_to "Delete Account", sessions_path, method: :delete, class: "text-white bg-gray-500 focus:ring-4 font-medium rounded-lg px-5 py-3 mr-2 w-full" %>
</div>

rails/app/views/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full" data-controller="bridge--buton">
  <h1 class="font-bold text-4xl">New user</h1>

  <%= render "form", user: @user %>

  <%= link_to "Or Login", new_session_path,
    "data-bridge--buton-target": "login", "data-brige--button-title": "Login",
    class: "ml-2 rounded-lg py-3 px-5 bg-gray-500 text-white inline-block font-medium" %>
</div>