rails/config/routes.rb
Rails.application.routes.draw do
  get 'pages/home', to: 'pages#home', as: :get_started
  get 'pages/info', to: 'pages#info', as: :info

  resources :job_applications do
    resources :interviews, except: %i[index]
  end
  resources :users, except: %i[index]
  resources :sessions, only: %i[new create] do
    delete :destroy, on: :collection
  end
  post 'sessions/create', to: 'sessions#create', as: 'login'

  resources :configurations, only: [] do
    get :ios, on: :collection
  end

  root 'pages#home'
end

rails/app/models/job_application.rb
# frozen_string_literal: true

class JobApplication < ApplicationRecord
  belongs_to :user
  has_many :interviews, dependent: :destroy

  validates :position, :status, :applied_at, :company_name, :location, presence: true

  enum status: { applied: 0, in_progress: 1, rejected: 2, declined: 3, offer_received: 4, paused: 5 }
  enum priority: { low: 0, medium: 1, high: 2 }
  enum avaliation: { bad: 0, regular: 1, good: 2, excellent: 3 }
end

rails/app/controllers/job_applications_controller.rb
# frozen_string_literal: true

class JobApplicationsController < ApplicationController
  before_action :set_job_application, only: %i[show edit update destroy]

  def index
    @job_applications = current_user.job_applications.order(created_at: :desc)
  end

  def show
    @interviews = @job_application.interviews.order(interview_at: :desc)
  end

  def new
    @job_application = JobApplication.new
  end

  def edit; end

  def create
    @job_application = JobApplication.new(job_application_params)

    respond_to do |format|
      if @job_application.save
        format.html do
          redirect_to job_application_url(@job_application), notice: 'Job application was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @job_application.update(job_application_params)
        format.html do
          redirect_to job_application_url(@job_application), notice: 'Job application was successfully updated.'
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job_application.destroy!

    respond_to do |format|
      format.html { redirect_to job_applications_url, notice: 'Job application was successfully destroyed.' }
    end
  end

  private

  def set_job_application
    @job_application = JobApplication.find(params[:id])
  end

  def job_application_params
    params.require(:job_application).permit(
      :company_name,
      :position, :status,
      :applied_at,
      :applied_via,
      :contact_name,
      :contact_email,
      :priority,
      :location,
      :personal_feedback,
      :avaliation
    ).merge(user: current_user)
  end
end

rails/app/views/job_applications/_form.html.erb
<%= form_with(model: job_application, class: "contents") do |form| %>
  <% if job_application.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(job_application.errors.count, "error") %> prohibited this job_application from being saved:</h2>

      <ul>
        <% job_application.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :company_name, "Company Name", class: "block mb-2 text-base font-medium text-gray-900"  %>
    <%= form.text_field :company_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :position, "Position Title", class: "block mb-2 text-base font-medium text-gray-900"  %>
    <%= form.text_field :position, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :location, "Location", class: "block mb-2 text-base font-medium text-gray-900"  %>
    <%= form.text_field :location, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status, "Status", class: "block mb-2 text-base font-medium text-gray-900"  %>
    <%= form.select :status, JobApplication.statuses.keys.map { |status| [status.titleize, status] }, { include_blank: false }, { class: "bg-white border border-gray-300 text-gray-900 text-base rounded-lg block w-full p-2.5" } %>
  </div>

  <div class="my-5">
    <%= form.label :applied_at, "When did you applied?", class: "block mb-2 text-base font-medium text-gray-900"  %>
    <%= form.date_field :applied_at, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :applied_via, "How did you applied?", class: "block mb-2 text-base font-medium text-gray-900"  %>
    <%= form.text_field :applied_via, placeholder: "Linkedin/Direct message...", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :priority, "Priority", class: "block mb-2 text-base font-medium text-gray-900"  %>
    <%= form.select :priority, JobApplication.priorities.keys.map { |priority| [priority.titleize, priority] }, { include_blank: false }, { class: "bg-white border border-gray-300 text-gray-900 text-base rounded-lg block w-full p-2.5" } %>
  </div>

  <div class="my-5">
    <%= form.label :contact_name, "Contact Name (Recruiter)", class: "block mb-2 text-base font-medium text-gray-900"  %>
    <%= form.text_field :contact_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :contact_email, "Contact Email (Recruiter)", class: "block mb-2 text-base font-medium text-gray-900"  %>
    <%= form.text_field :contact_email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :avaliation, "Personal Avaliation", class: "block mb-2 text-base font-medium text-gray-900"  %>
    <%= form.select :avaliation, JobApplication.avaliations.keys.map { |avaliation| [avaliation.titleize, avaliation] }, { include_blank: true }, { class: "bg-white border border-gray-300 text-gray-900 text-base rounded-lg block w-full p-2.5" } %>
  </div>

  <div class="my-5">
    <%= form.label :personal_feedback, "Personal Feedback", class: "block mb-2 text-base font-medium text-gray-900"  %>
    <%= form.text_area :personal_feedback, rows: 5, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :improvements, "Improvements", class: "block mb-2 text-base font-medium text-gray-900"  %>
    <%= form.text_area :improvements, rows: 5, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline flex justify-between	">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-ptpurple text-white inline-block font-medium cursor-pointer" %>
    <%= link_to "Back", job_applications_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

rails/app/views/job_applications/_job_application.html.erb
<div id="<%= dom_id job_application %>">
  <% if action_name == "index" %>
    <%= link_to job_application do %>
      <div class="w-full p-6 bg-white border border-gray-200 rounded-lg shadow mb-4">
        <h5 class="mb-2 text-lg font-bold tracking-tight text-gray-900">
          <%= job_application.position %> at <%= job_application.company_name %>
        </h5>

        <p class="mb-3 font-normal text-gray-700">
          <span class="bg-gray-500 text-white text-sm font-medium me-2 px-2.5 py-1.5 rounded">
            <%= job_application.status %>
          </span>
          <span class="bg-ptpurple text-white text-sm font-medium me-2 px-2.5 py-1.5 rounded">
            <%= job_application.priority %> priority
          </span>
        </p>

        <p class="font-medium text-gray-700 mb-3">
          <strong>Location:</strong> <%= job_application.location %>
        </p>

        <p class="font-medium text-gray-700">
          <strong>Applied at:</strong> <%= job_application.applied_at.strftime("%m-%d-%Y") %>
        </p>
      </div>
    <% end %>
  <% else %>
    <div class="w-full px-1 py-3">
      <h5 class="mb-3 text-xl font-bold tracking-tight text-gray-900">
        <%= job_application.position %> at <%= job_application.company_name %>
      </h5>

      <p class="mb-4 font-normal text-gray-700">
        <span class="bg-gray-500 text-white text-sm font-medium me-2 px-2.5 py-1.5 rounded">
          <%= job_application.status %>
        </span>
        <span class="bg-ptpurple text-white text-sm font-medium me-2 px-2.5 py-1.5 rounded">
          <%= job_application.priority %> priority
        </span>
      </p>

      <p class="font-medium text-gray-700 mb-3">
        <strong>Location:</strong> <%= job_application.location %>
      </p>

      <p class="font-medium text-gray-700 mb-3">
        <strong>Applied at:</strong> <%= job_application.applied_at.strftime("%m-%d-%Y") %>
      </p>

      <p class="font-medium text-gray-700 mb-3">
        <strong>Applied via:</strong> <%= job_application.applied_via %>
      </p>

      <hr>

      <% if job_application.contact_name.present? || job_application.contact_email.present? %>
        <p class="mt-1 font-normal text-gray-700">
          <span class="bg-gray-400 text-white text-xs me-2 px-1.5 py-1 rounded">
            Contact Info
          </span>
        </p>
      <% end %>

      <% if job_application.contact_name.present? %>
        <p class="mt-2 mb-5">
          <strong class="block font-medium mb-1">Contact name:</strong>
          <%= job_application.contact_name %>
        </p>
      <% end %>

      <% if job_application.contact_email.present? %>
        <p class="my-5">
          <strong class="block font-medium mb-1">Contact email:</strong>
          <%= job_application.contact_email %>
        </p>
      <% end %>

      <hr>

      <% if job_application.personal_feedback.present? || job_application.avaliation.present? || job_application.improvements.present? %>
        <p class="mt-1 font-normal text-gray-700">
          <span class="bg-gray-400 text-white text-xs me-2 px-1.5 py-1 rounded">
            Personal check
          </span>
        </p>

        <% if job_application.personal_feedback.present? %>
          <p class="my-5">
            <strong class="block font-medium mb-1">Personal feedback:</strong>
            <%= job_application.personal_feedback %>
          </p>
        <% end %>

        <% if job_application.avaliation.present? %>
          <p class="my-5">
            <strong class="block font-medium mb-1">Avaliation:</strong>
            <%= job_application.avaliation %>
          </p>
        <% end %>

        <% if job_application.improvements.present? %>
          <p class="my-5">
            <strong class="block font-medium mb-1">What can i improve on?:</strong>
            <%= job_application.improvements %>
          </p>
        <% end %>

        <hr>
      <% end %>

      <div class="w-full mt-2">
        <div class="flex justify-between items-center mb-4">
          <h5 class="mt-2 text-lg font-bold tracking-tight text-gray-900">
            Interview Steps
          </h5>

          <div class="flex direction-row">
            <%= link_to new_job_application_interview_path(job_application), class: "mt-2 rounded-lg py-2 px-3 bg-ptpurple text-white block font-medium" do %>
              <%= inline_svg_tag("icons/plus.svg", style: "max-height: 30px; max-width: 30px; color: white") %>
            <% end %>
          </div>
        </div>

      <div id="interviews" class="min-w-full">
        <%= render @interviews %>
      </div>
    </div>

    <hr>

  <% end %>
</div>

rails/app/views/job_applications/edit.html.erb
<div class="mx-auto md:w-2/3 w-full pb-4">
  <h1 class="font-bold text-2xl">Editing job application</h1>

  <%= render "form", job_application: @job_application %>

</div>

rails/app/views/job_applications/index.html.erb
<%= content_for :title, "My Job Applications" %>

<div class="w-full" data-controller="bridge--button">
  <div class="flex justify-between items-center mb-4">
    <h1 class="font-bold text-2xl turbo-native:hidden">Job Applications</h1>
    <div class="flex direction-row">
      <%= link_to new_job_application_path, "data-bridge-image": "plus", class: " rounded-lg py-1.5 px-2 bg-ptpurple text-white block font-medium turbo-native:hidden" do %>
        <%= inline_svg_tag("icons/plus.svg", style: "max-height: 30px; max-width: 30px; color: white") %>
      <% end %>
    </div>
  </div>

  <div id="job_applications" class="min-w-full">
    <%= render @job_applications %>
  </div>
</div>

rails/app/views/job_applications/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-2xl">New job application</h1>

  <%= render "form", job_application: @job_application %>

</div>

rails/app/views/job_applications/show.html.erb
<% content_for :title, @job_application.company_name %>

<div class="w-full pb-5" data-controller="bridge--menu">
  <div class="mx-auto">

    <%= render @job_application %>

    <div class="flex flex-row justify-between space-x-2 mt-4">
      <%= link_to "Edit", edit_job_application_path(@job_application), "data-bridge--menu-target": "edit", class: "flex-1 text-center rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium turbo-native:hidden" %>

      <%= link_to "Delete", job_application_path(@job_application), data: { turbo_method: :delete, turbo_confirm: "Are you sure?", "bridge--menu-target": "delete" }, class: "flex-1 text-center rounded-lg py-3 text-white px-5 bg-gray-500 inline-block font-medium turbo-native:hidden" %>

      <%= link_to "Back", job_applications_path, class: "flex-1 ml-2 text-center rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium turbo-native:hidden" %>
    </div>
  </div>
</div>