rails/config/routes.rb
Rails.application.routes.draw do
  get 'pages/home', to: 'pages#home', as: :get_started
  get 'pages/info', to: 'pages#info', as: :info

  resources :job_applications do
    resources :interviews, except: %i[index]
  end
  resources :users, except: %i[index]
  resources :sessions, only: %i[new create] do
    delete :destroy, on: :collection
  end
  post 'sessions/create', to: 'sessions#create', as: 'login'

  resources :configurations, only: [] do
    get :ios, on: :collection
  end

  root 'pages#home'
end

rails/app/views/pages/home.html.erb
<div class="mx-auto md:w-2/3 w-full pt-4">
  <p class="mb-6">Yay! It's very good to see you here.</p>
  <%= link_to "Get Started", new_user_path, class: "rounded-lg py-3 px-5 bg-ptpurple text-white font-medium" %>
</div>

rails/app/views/pages/info.html.erb
<% content_for(:title, "Recent Activities")%>

<div class="mx-auto w-full pt-4">
  <h1 class="font-bold text-2xl mb-4 turbo-native:hidden">Recent Activities</h1>

  <h2 class="font-bold text-xl mb-4">Last Job Applications</h2>

  <ul class="max-w-md space-y-1 text-gray-700 list-disc list-inside pl-4 mb-6">
    <% @job_applications.each do |job_application| %>
      <li class="flex items-center">
        <span class="mr-2">👜</span>
        <div>
          <%= job_application.position %> at <strong><%= job_application.company_name %></strong>
        </div>
      </li>
    <% end %>
  </ul>

  <h2 class="font-bold text-xl mb-4">Next Interviews</h2>

  <ul class="max-w-md space-y-1 text-gray-700 list-disc list-inside pl-4 mb-8">
    <% @interviews.each do |interview| %>
      <li class="flex items-center">
        <span class="mr-2">📅</span>
        <div>
          <%= interview.job_application.company_name %> - <%= humanized_text(interview.interview_type) %>
        </div>
      </li>
    <% end %>
  </ul>

  <%= link_to "Go to Job Applications", job_applications_path, class: "rounded-lg py-3 px-5 bg-ptpurple text-white font-medium block text-center mt-4 w-full" %>
</div>

<%= link_to "Edit User", edit_user_path(current_user), "data-controller": "bridge--button", "data-bridge-image": "person.circle", class: "invisible" %>