rails/config/routes.rb
Rails.application.routes.draw do
  get 'pages/home', to: 'pages#home', as: :get_started
  get 'pages/info', to: 'pages#info', as: :info

  resources :job_applications do
    resources :interviews, except: %i[index]
  end
  resources :users, except: %i[index]
  resources :sessions, only: %i[new create] do
    delete :destroy, on: :collection
  end
  post 'sessions/create', to: 'sessions#create', as: 'login'

  resources :configurations, only: [] do
    get :ios, on: :collection
  end

  root 'pages#home'
end

rails/app/controllers/interviews_controller.rb
# frozen_string_literal: true

class InterviewsController < ApplicationController
  before_action :set_job_application
  before_action :set_interview, only: %i[show edit update destroy]

  def show; end

  def new
    @interview = @job_application.interviews.build
  end

  def edit; end

  def create
    @interview = @job_application.interviews.build(interview_params)

    respond_to do |format|
      if @interview.save
        @job_application.interviews.reload

        format.html do
          redirect_to job_application_interview_path(@job_application, @interview), notice: 'Interview was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @interview.update(interview_params)
        format.html do
          redirect_to job_application_interview_path(@job_application, @interview), notice: 'Interview was successfully updated.'
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @interview.destroy!

    respond_to do |format|
      format.html { redirect_to job_application_url(@job_application), notice: 'Interview was successfully destroyed.' }
    end
  end

  private

  def set_job_application
    @job_application = current_user.job_applications.find(params[:job_application_id])
  end

  def set_interview
    @interview = Interview.find(params[:id])
  end

  def interview_params
    params.require(:interview).permit(:interview_at, :interview_type, :details, :interviewers_info, :url)
  end
end

rails/app/views/interviews/_form.html.erb
<%= form_with(model: [@job_application, interview], class: "contents") do |form| %>
  <% if interview.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(interview.errors.count, "error") %> prohibited this interview from being saved:</h2>

      <ul>
        <% interview.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :interview_at %>
    <%= form.date_field :interview_at, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :interview_type, "Interview Type", class: "block mb-2 text-base font-medium text-gray-900"  %>
    <%= form.select :interview_type, Interview.interview_types.keys.map { |interview_type| [interview_type.titleize, interview_type] }, { include_blank: false }, { class: "bg-white border border-gray-300 text-gray-900 text-base rounded-lg block w-full p-2.5" } %>
  </div>

  <div class="my-5">
    <%= form.label :details %>
    <%= form.text_area :details, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :interviewers_info %>
    <%= form.text_area :interviewers_info, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :url %>
    <%= form.text_field :url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline flex justify-between	">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-ptpurple text-white inline-block font-medium cursor-pointer" %>
    <%= link_to "Back", job_application_path(@job_application), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

rails/app/views/interviews/_interview.html.erb
<div id="<%= dom_id interview %>">
    <%= link_to job_application_interview_path(interview.job_application_id, interview) do %>
      <div class="w-full px-3 py-0.5 bg-white border border-gray-200 rounded-lg shadow mt-4 pb-3">

        <p class="font-medium text-gray-700 my-3">
          <span class="bg-ptpurple text-white text-sm font-medium me-2 px-2.5 py-1.5 rounded">
            <%= humanized_text(interview.interview_type) %>
          </span>
        </p>

        <% if interview.interview_at.present? %>
          <p class="font-medium text-gray-700 my-3">
            <strong>When:</strong> <%= interview.interview_at.strftime("%m-%d-%Y") %>
          </p>
        <% end %>

        <p class="my-3">
          <p class="font-medium text-gray-700 my-3">
            <strong>Details:</strong>
          </p>

          <p class="text-sm"><%= interview.details %></p>
        </p>

        <% if interview.interviewers_info.present? %>
          <p class="my-3">
            <p class="font-medium text-gray-700 my-3">
              <strong>Interviewers Info:</strong>
            </p>
            <%= interview.interviewers_info %>
          </p>
        <% end %>

        <% if interview.url.present? %>
          <p class="my-3">
            <p class="font-medium text-gray-700 my-3">
              <strong>URL/Link:</strong>
            </p>
            <%= interview.url %>
          </p>
        <% end %>
      </div>
    <% end %>

  <% if action_name != "show" %>
    <%= link_to "Show this interview", job_application_interview(interview), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this interview", edit_job_application_interview_path(interview), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

rails/app/views/interviews/edit.html.erb
<div class="mx-auto md:w-2/3 w-full pb-6">
  <h1 class="font-bold text-4xl">Editing interview</h1>

  <%= render "form", interview: @interview %>
</div>

rails/app/views/interviews/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Interviews</h1>
    <%= link_to "New interview", new_interview_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="interviews" class="min-w-full">
    <%= render @interviews %>
  </div>
</div>

rails/app/views/interviews/new.html.erb
<div class="mx-auto md:w-2/3 w-full pb-6">
  <h1 class="font-bold text-4xl">New interview</h1>

  <%= render "form", interview: @interview %>
</div>

rails/app/views/interviews/show.html.erb
<% content_for(:title, humanized_text(@interview.interview_type)) %>

<div class="w-full pb-5">
  <div class="mx-auto" data-controller="bridge--menu">
    <%= render @interview %>

    <div class="flex flex-row justify-between space-x-2 mt-6">
      <%= link_to "Edit", edit_job_application_interview_path(@interview.job_application_id, @interview), "data-bridge--menu-target": "edit", class: "flex-1 text-center rounded-lg py-3 px-5 bg-gray-200 inline-block font-medium turbo-native:hidden" %>

      <%= link_to "Delete", job_application_interview_path(@interview.job_application_id, @interview), data: { turbo_method: :delete, "bridge--menu-target": "delete", turbo_confirm: "Are you sure?" }, class: "flex-1 text-center rounded-lg py-3 text-white px-5 bg-gray-500 inline-block font-medium turbo-native:hidden" %>

      <%= link_to "Back", job_application_path(@interview.job_application), class: "flex-1 ml-2 text-center rounded-lg py-3 px-5 bg-gray-200 inline-block font-medium turbo-native:hidden" %>
    </div>
  </div>
</div>